<?php

/**
 * Implementation of hook_menu().
 */
function eurami_menu() {
  $items = array();

  $items['admin/eurami'] = array(
    'title' => 'Eurami',
    'description' => 'Eurami customization settings',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'eurami_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
  );

  $items['admin/eurami/settings'] = array(
    'title' => 'General settings',
    'description' => 'Set general parameters that are specific to the Eurami project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eurami_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
    'file' => 'includes/eurami.admin.inc',
  );
  
  return $items;
}

function eurami_admin_menu_block_page() {
  $item = menu_get_item();
  if ($content = system_admin_menu_block($item)) {
    $output = theme('admin_block_content', $content);
  }
  else {
    $output = t('You do not have any administrative items.');
  }
  return $output;
}

/**
 * Implementation of hook_form_alter().
 */

function eurami_form_alter(&$form, $form_state, $form_id) {
  switch($form_id) {
    case 'comment_form':
      foreach ($form['comment_filter']['format'] as $i => $filter) {
        if (is_int($i) && !$filter['#type']) {
          $form['comment_filter']['format'][$i]['#value'] = '';
          $form['comment_filter']['format'] = '';
          unset($form['preview']);
          unset($form['_author']);
        }
      }
      break;
  }
}

function getAccreditationInfoFromCompany($company_id, &$variables){
  $accreditation_view = views_get_view('get_accreditation_for_company');
  $accreditation_view->set_arguments(array($company_id));
  $accreditation_view->execute();
  
  if (empty($accreditation_view->result[0]->node_data_field_accreditiation_company_field_accreditiation_from_value)) {
    $variables['accreditation_status'] = t('Not accredited');
  }
  else {
    $variables['accreditation_status'] = $accreditation_view->result[0]->node_data_field_accreditiation_company_field_acc_type_value;
    
    //date when $accreditation is valid
    $from = $accreditation_view->result[0]->node_data_field_accreditiation_company_field_accreditiation_from_value;
    $to = $accreditation_view->result[0]->node_data_field_accreditiation_company_field_accreditiation_from_value2;
    
    if(!empty($from) && !empty($to)) {
      $variables['accreditation_from'] = date('d/m/Y', strtotime($from));
      $variables['accreditation_to'] = date('d/m/Y', strtotime($to));
    }
  }
}

/**2010-11-08
 * Implementation of hook_preprocess_node().
 */
function eurami_preprocess_node(&$variables) {
  if ($variables['type'] == 'company') {
    getAccreditationInfoFromCompany($variables['nid'], $variables);//add some values to $variables by reference
  }
}

